services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=kertaskerja_realisasi_pemda'
      - 'POSTGRES_PASSWORD=ChangeMyPassword'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
